version: '3.9'

networks:
  net:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: todo_mysql_1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin1
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "./db/init.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - net

volumes:
  mysql_data:
    driver: local
