"""first_migration

Revision ID: 84236edf6907
Revises: 
Create Date: 2024-05-21 00:48:24.327003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84236edf6907'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'todos',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('title', sa.String(length=100), nullable=True),
        sa.Column('complete', sa.Boolean, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
